apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      initContainers:
      - name: init-airflow-dags
        image: busybox
        command: ['sh', '-c', 'cp -r /usr/local/airflow/persistent/* /opt/airflow/dags/']
        volumeMounts:
        - name: airflow-persistent-storage
          mountPath: /usr/local/airflow/persistent
        - name: airflow-dags
          mountPath: /opt/airflow/dags    
      containers:
      - name: airflow-webserver
        image: apache/airflow:2.3.0
        command: ["/bin/bash", "-c"]
        args:
          - airflow db init &&        
            airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
            airflow webserver --port 8080 
        ports:
        - containerPort: 8080
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "SequentialExecutor"
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "sqlite:////usr/local/airflow/airflow.db"
        - name: _AIRFLOW_WWW_USER_USERNAME 
          value: "admin"
        - name: _AIRFLOW_WWW_USER_PASSWORD 
          value: "admin123"      
        volumeMounts:
        - name: airflow-config
          mountPath: /usr/local/airflow/airflow.cfg
          subPath: airflow.cfg
        - name: airflow-database
          mountPath: /usr/local/airflow
        - name: airflow-persistent-storage
          mountPath: /usr/local/airflow/persistent
      - name: airflow-scheduler
        image: apache/airflow:2.3.0
        command: ["/bin/bash", "-c"]
        args:
          - airflow scheduler
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "SequentialExecutor"
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "sqlite:////usr/local/airflow/airflow.db"
        volumeMounts:
        - name: airflow-config
          mountPath: /usr/local/airflow/airflow.cfg
          subPath: airflow.cfg
        - name: airflow-database
          mountPath: /usr/local/airflow
        - name: airflow-persistent-storage
          mountPath: /usr/local/airflow/persistent
      volumes:
      - name: airflow-config
        configMap:
          name: airflow-config
      - name: airflow-database
        emptyDir: {}
      - name: airflow-persistent-storage
        persistentVolumeClaim:
          claimName: airflow-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  airflow.cfg: |
    [webserver]
    base_url = http://192.168.49.2:32128
    web_server_host = 0.0.0.0
    web_server_port = 8080
    rbac = True
    auth_backend = airflow.api.auth.backend.basic_auth
    [core]
    dags_folder = /usr/local/airflow/dags
    base_log_folder = /usr/local/airflow/logs
    executor = SequentialExecutor
    sql_alchemy_conn = sqlite:////usr/local/airflow/airflow.db
    load_examples = True
